apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dectest-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dectest.k8test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "decisions-dev.fullname" . }}
            port:
              number: 80